version: '3'

services:
  pleroma:
    build: .
    container_name: pleroma_app
    ports:
      - "4000:4000"
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./uploads:/pleroma/uploads
      - ./config:/pleroma/config
      - ./priv:/pleroma/priv
    networks:
      - front
      - back

  db:
    image: postgres:11-alpine
    container_name: pleroma_db
    restart: always
    environment:
      POSTGRES_USER: pleroma
      POSTGRES_PASSWORD: pleroma
      POSTGRES_DB: pleroma
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - back

networks:
  front:
    external:
      name: freccia-production
  back:
    external:
      name: pleroma-backend
